builds:
  - id: ds-load-hubspot
    main: ./cmd/ds-load-hubspot
    binary: ds-load-hubspot
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/ds-load/sdk/common/version.ver={{.Version}}
      - -X github.com/aserto-dev/ds-load/sdk/common/version.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/ds-load/sdk/common/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - format: zip
    rlcp: true
    files:
      - LICENSE
      - README.md
    name_template: >-
      ds-load-hubspot_{{.Version}}_{{ .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}"

release:
  github:
    owner: aserto-demo
    name: ds-load-hubspot

  draft: false
  prerelease: auto
  name_template: "ds-load-hubspot {{.Tag}}"

brews:
  -
    name: ds-load-hubspot

    tap:
      owner: aserto-dev
      name: homebrew-tap
      token: "{{ .Env.ASERTO_TAP }}"

    url_template: "https://github.com/aserto-demo/ds-load-hubspot/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    
    download_strategy: CurlDownloadStrategy

    commit_author:
      name: Aserto Bot
      email: github-bot@aserto.com

    homepage: "https://docs.aserto.com/"

    description: "DS Load Hubspot"

    license: "Apache 2.0"

    skip_upload: false

    test: |
      system "#{bin}/ds-load-hubspot version"
    install: |
      bin.install "ds-load-hubspot"
